language: java
sudo: false
install: true

#addons:
#  sonarcloud:
#    organization: "cloudyrock"
#    token:
#      secure: "$SONAR_TOKEN"

jdk:
  - oraclejdk8

script:
#  - sonar-scanner
  - mvn clean sonar:sonar -Dsonar.projectKey=com.github.cloudyrock.dimmer -Dsonar.organization=cloudyrock -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b3ad74729ae5d41a7248e50e686d44b755f3a092 -Dmaven.test.failure.ignore=false

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
